//! Markdown → Typst markup, for the PDF export.
//!
//! The output is Typst *source*, plain text, which the Typst CLI compiles to a
//! PDF. It is not HTML and not a PDF library API: keeping the compilation in a
//! subprocess is what stops a PDF engine from becoming a dependency of the app.
//!
//! # Why the output is safe
//!
//! This looks like the HTML renderer's threat model turned up again —
//! untrusted markdown reaching a compiler — and it is the same argument with a
//! different consequence. The output is a language *we generate in full*: there
//! is no template where document text lands as markup. Everything from the
//! document goes through [`escape_text`], which backslash-escapes every
//! character Typst gives meaning to, so a `$` in prose stays a `$` and cannot
//! open math, a `#` cannot start a code expression, and a `` ` `` cannot open a
//! raw block.
//!
//! That property is why no document text is ever placed inside a Typst string
//! literal passed to `#raw`/`#link`/`#image`. It would need its own escaping,
//! and one mistake there is not a rendering bug: Typst source can read files
//! (`#read`), so a breakout would be a sandbox escape rather than a typo. Code
//! spans and blocks are emitted as backtick *fences* instead, where the content
//! is literal by construction.
//!
//! The only strings in the output are the destinations of links and images. A
//! link's goes through the same scheme check the HTML renderer uses; an image's
//! is a *path*, and a path that resolved to a file inside the note's own folder
//! is the narrowest thing it can be — see below.
//!
//! # The second chokepoint: an image path is a path, not text
//!
//! Everything above is about *what the document says*. An image destination is
//! also a path the compiler will open, and Typst is a filesystem reader: it
//! resolves one against the source file and reads whatever it lands on. Two
//! things follow, and neither is a rendering bug.
//!
//! * **A path that does not resolve fails the whole document.** Typst has no
//!   try/catch: one `#image` to a file that is not there is a compile error with
//!   a line number and *no PDF*. A note with a stale image link could not be
//!   exported at all, and what the user was told was that exporting did not
//!   work.
//! * **A path that resolves can name anything.** `![](/etc/passwd)` in a note
//!   that gets shared puts a file from the disk into the PDF. Typst's own
//!   `--root` refuses a `..` that escapes it and reinterprets an absolute path
//!   as relative to it, but it *follows a symlink* that sits inside the root to
//!   whatever that link points at — measured against the 0.15.1 CLI, not
//!   assumed. CodeDocs opens folders the user did not write, so a note is
//!   untrusted input about its own files.
//!
//! So [`markdown_to_typst`] is given the note's folder and resolves every image
//! against it *before* the reference is emitted. See [`image_argument`] for the
//! two questions and why they are asked where the source is generated rather
//! than in the subprocess, where the only available answer is the error message.
//!
//! # What Typst actually accepts
//!
//! The mapping is not "markdown in, Typst out" by intuition; every construct
//! below was compiled with the real CLI (0.15.1) before being written down. Two
//! surprises are worth keeping in mind:
//!
//! * A bare `$` in prose breaks the *whole document*, not just its paragraph:
//!   `$5 y $10` is an unclosed math delimiter and `typst compile` fails. Hence
//!   the escape set.
//! * Typst has no syntax for `- [ ]`, so task lists are drawn by hand with
//!   [`checkbox`]; passing `- [ ]` through emits those characters literally.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use pulldown_cmark::{CowStr, Event, Parser, Tag, TagEnd};

use super::math::{split_math, MathPiece};
use super::parser_options;
use super::sanitize::is_safe_url;
use super::typst_math::{tex_to_typst, tex_to_typst_blocks};

/// Page setup emitted before the document.
///
/// Deliberately no `font:`: an unavailable font name fails the compilation, and
/// the CLI's defaults (Libertinus Serif, plus the math and mono faces it
/// embeds) already look like a document.
const PREAMBLE: &str = "\
// Generated by CodeDocs from a Markdown note. Edit the note, not this file.
#set page(paper: \"a4\", margin: 2.5cm)
#set text(size: 11pt)
#set par(justify: true)
";

/// Render markdown as Typst markup.
///
/// The result is a complete `.typ` document: [`PREAMBLE`] plus the body.
/// Compiling it is the caller's job (the `export_pdf` command), which keeps
/// this function pure and testable without a Typst binary around.
///
/// # `note_folder` is not an optional extra
///
/// It is the folder the note itself lives in, and it is what every image
/// reference in the document is resolved against — and refused with. Typst can
/// read any file the process can reach, and it resolves a link *inside* the root
/// to whatever that link points at, so a note that names its own images is a
/// note that can name any file on the disk and have it read into a PDF the user
/// then shares. The same is true of an image that does not exist: Typst has no
/// way to catch a failed read, so one unresolvable `#image` fails the whole
/// compilation and no PDF comes out at all.
///
/// So the check happens here, where the `.typ` is generated, and there is
/// nothing to forget: a caller cannot produce this output without saying where
/// the note is, and a path that does not resolve to a file inside that folder
/// becomes a marker that names it instead of a reference the compiler would choke
/// on. A folder that cannot be resolved at all — the answer on a platform with
/// no filesystem to ask, which is the wasm frontend — takes the same
/// fail-closed road: every image is a marker.
pub fn markdown_to_typst(content: &str, note_folder: &Path) -> String {
    let events: Vec<Event<'_>> = Parser::new_ext(content, parser_options()).collect();
    // Two passes over the parsed events. The first renders the footnote
    // definitions, because in markdown a *reference* almost always comes first
    // — `#footnote[…]` is emitted at the reference site, so the body has to be
    // known before the body that refers to it starts.
    let footnotes = collect_footnotes(&events, note_folder);
    let mut writer = Writer {
        link_stack: Vec::new(),
        suppress_image_text: 0,
        footnotes,
        in_footnote: false,
        depth: 0,
        quote_depth: 0,
        // Resolved once: the containment check below compares canonical paths,
        // and doing it per image would be a syscall per image for nothing. A
        // folder that cannot be canonicalised stays `None`, which is the
        // fail-closed answer rather than "no check".
        note_folder: note_folder.canonicalize().ok(),
    };
    let mut body = String::new();
    writer.blocks(&events, &mut body);
    format!("{PREAMBLE}\n{}", body.trim_matches('\n'))
}

/// The Typst spelling of one task-list marker.
///
/// Drawn with Typst primitives rather than with a character: U+2610 and U+2713
/// are in none of the faces the CLI embeds, so a literal `☐` renders as a blank
/// box — checked against the real compiler, rendering the page to an image. The
/// check mark is a `curve`, so it needs no font either.
fn checkbox(checked: bool) -> &'static str {
    const UNCHECKED: &str = "#box(stroke: 0.5pt, width: 0.75em, height: 0.75em, inset: 0pt)[]";
    const CHECKED: &str = concat!(
        "#box(stroke: 0.5pt, width: 0.9em, height: 0.9em, inset: 0pt)[",
        "#align(left + top)[",
        "#curve(curve.move((0.14em, 0.32em)), curve.line((0.34em, 0.58em)), ",
        "curve.line((0.70em, 0.10em)), stroke: 0.9pt)",
        "]",
        "]",
    );
    if checked {
        CHECKED
    } else {
        UNCHECKED
    }
}

/// Characters escaped before any document text reaches the output.
///
/// Every character Typst's markup gives a meaning to. Escaping unconditionally
/// — rather than only where a character happens to sit at the start of a line —
/// is what makes the output a function of the document instead of of its
/// context: `=`, `-`, `+` and `/` become heading and list markers only at the
/// start of a line, and where a line starts is not something this module always
/// knows, because a soft break inside a paragraph can produce one.
///
/// The set was verified against the real compiler: each of these escapes is
/// accepted and produces the bare character. `.` is deliberately absent, it
/// carries no meaning in markup (`...` becoming an ellipsis is cosmetic).
fn escape_text(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for ch in text.chars() {
        if matches!(
            ch,
            '\\' | '`'
                | '*'
                | '_'
                | '$'
                | '#'
                | '@'
                | '<'
                | '>'
                | '['
                | ']'
                | '~'
                | '-'
                | '+'
                | '='
                | '/'
                | '\''
                | '"'
                | '{'
                | '}'
        ) {
            out.push('\\');
        }
        out.push(ch);
    }
    out
}

/// Document text inside a Typst string literal.
///
/// The one place a string is unavoidable — a URL has to be one — and the reason
/// the escaping above is not enough on its own: a `\` or a `"` in the value
/// would otherwise close the literal and turn the rest of the URL into code.
/// Escaping both is total, since every character that can end a string literal
/// is escaped and no byte of the value can escape from inside it.
fn quote_string(value: &str) -> String {
    let mut out = String::with_capacity(value.len() + 2);
    out.push('"');
    for ch in value.chars() {
        if ch == '\\' || ch == '"' {
            out.push('\\');
        }
        out.push(ch);
    }
    out.push('"');
    out
}

/// Longest run of backticks in `text`.
fn longest_backtick_run(text: &str) -> usize {
    let mut longest = 0;
    let mut current = 0;
    for ch in text.chars() {
        if ch == '`' {
            current += 1;
            longest = longest.max(current);
        } else {
            current = 0;
        }
    }
    longest
}

/// A backtick fence long enough to contain `content`.
///
/// Typst ends a raw block at a run of backticks as long as the opening fence,
/// so code containing backticks needs a longer fence or the block closes early
/// and the rest of the code is typeset as prose.
///
/// The rule is `max(3, longest + 2)`, measured against the real compiler for
/// inner runs of 0 to 5. The two extra backticks are not superstition — each
/// weaker rule fails differently, and only one of them says so:
///
/// * `longest + 1` is wrong for a single inner backtick. `` `` `a`b` `` ``
///   compiles *successfully* and prints `ab`: the backtick silently vanishes.
/// * `longest` equal to the fence does not close the block at all — "unclosed
///   raw text", and no PDF.
///
/// The floor of three covers the other end: an inline fence shorter than three
/// does not get Typst's padded form, and the padding is what keeps the first
/// word of the code from being read as a language tag.
fn fence_for(content: &str) -> String {
    "`".repeat(fence_len(content))
}

/// How many backticks a fence for `content` needs. See [`fence_for`].
fn fence_len(content: &str) -> usize {
    (longest_backtick_run(content) + 2).max(3)
}

/// A code span, as an inline raw fence.
///
/// The single space *after* the opening fence is what stops Typst reading the
/// first word as a language tag — `` ```x``` `` swallows `x` as the tag and
/// prints nothing, and `` ```rust fn``` `` prints `fn` without `rust`. It is
/// also free: Typst consumes it as the separator between fence and content. A
/// space *before* the closing fence is not free — it stays in the output, which
/// is how `` `código `. `` came out as `código .`. Both measured by rendering
/// the page and reading the glyph positions back.
fn inline_code(code: &str) -> String {
    let fence = fence_for(code);
    format!("{fence} {code}{fence}")
}

/// The language of a fenced code block, or `None` for a plain one.
///
/// The info string is document text. It lands in Typst as a bare token, so it is
/// filtered down to what a language name can contain: a fence label such as
/// ```` ```{#x" onload="y} ```` must not become anything else. An unrecognised
/// name is harmless — Typst warns about it, it does not fail.
fn code_language(info: Option<&str>) -> Option<String> {
    let first = info?.split_whitespace().next()?;
    let name: String = first
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '+' | '#' | '-' | '.'))
        .collect();
    if name.is_empty() {
        None
    } else {
        Some(name)
    }
}

/// An image path for a Typst string and for the filesystem.
///
/// Typst paths are `/`-separated on every platform, so a Windows source path is
/// normalised rather than left with separators that would have to be doubled to
/// survive the string literal.
fn image_path(dest: &str) -> String {
    dest.replace('\\', "/")
}

/// Why an image reference did not become an `#image`.
///
/// Ordered the way the questions are asked, so the marker names the first thing
/// that is wrong rather than a downstream symptom of it.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum MissingImage {
    /// No such file, or the path could not be resolved at all.
    NotFound,
    /// It resolves to somewhere outside the note's own folder.
    Outside,
    /// It resolves, inside the folder, and it is a folder.
    NotAFile,
    /// The note's folder could not be resolved, so no path can be checked
    /// against anything.
    NoNoteFolder,
}

impl MissingImage {
    /// What the reader is told in the PDF, in place of the picture.
    fn reason(self) -> &'static str {
        match self {
            MissingImage::NotFound => "imagen que no existe",
            MissingImage::Outside => "imagen fuera de la carpeta de la nota",
            MissingImage::NotAFile => "la ruta no es un archivo",
            MissingImage::NoNoteFolder => "imagen sin carpeta de la nota donde buscarla",
        }
    }
}

/// The `#image` argument for `dest`, or the reason there is not one.
///
/// Two questions, both asked here rather than left to the compiler, because the
/// compiler cannot answer either one usefully:
///
/// 1. **Does it resolve?** A path that does not is an error, and Typst has no
///    try/catch — one unresolvable `#image` fails the whole compilation and the
///    user gets no PDF and no idea what was wrong with the note.
/// 2. **Does it land inside the note's folder?** Typst reads any file the
///    process can, and it follows a link that sits inside its root to the link's
///    target, so without this a note can name a path that reads a file from
///    anywhere on the disk into a document the user shares. CodeDocs opens
///    folders the user did not write, which is what makes a note's own image
///    paths untrusted input.
///
/// The spelling checked is the spelling emitted. Canonicalising one string and
/// writing another is how a check and a compiler end up disagreeing about where
/// a file is — and the emitted path stays the document's own, because the
/// generated source sits in the note's folder and Typst resolves relative to the
/// source.
fn image_argument(dest: &str, note_folder: Option<&Path>) -> Result<String, MissingImage> {
    let base = note_folder.ok_or(MissingImage::NoNoteFolder)?;
    let spelling = image_path(dest);
    // `canonicalize` resolves `..` *and* symlinks before the containment test,
    // so neither can be what carries a path out of the folder. It fails for
    // anything that is not there to resolve, which is the same answer: there is
    // no file, so there is nothing to reference.
    let resolved = base
        .join(&spelling)
        .canonicalize()
        .map_err(|_| MissingImage::NotFound)?;
    if !resolved.starts_with(base) {
        return Err(MissingImage::Outside);
    }
    // A directory resolves, is inside the folder, and is still not an image the
    // compiler can read — the same no-PDF failure, one check later.
    if !resolved.is_file() {
        return Err(MissingImage::NotAFile);
    }
    Ok(quote_string(&spelling))
}

/// Whether an image destination names something on this disk.
///
/// Everything else is dropped before a path is built out of it: a scheme or a
/// `//host` is a URL, and the compiler has no network to fetch it with.
fn is_local_image(dest: &str) -> bool {
    is_safe_url(dest) && !dest.contains("://") && !dest.starts_with("data:")
}

/// An image that cannot be included, as something visible on the page.
///
/// The export has to come out even when a file is missing, and a picture that
/// quietly leaves a hole is the failure this whole check is not: the reader has
/// to be able to tell that something was there. The path is document text and
/// goes through [`escape_text`] like every other character from the document —
/// the marker puts it inside a Typst content block, and an unescaped `]` would
/// end the block early and the rest of the path would become markup.
fn missing_image(dest: &str, why: MissingImage) -> String {
    format!("#emph[{}: {}]", why.reason(), escape_text(dest))
}

/// Renders an event stream into Typst markup.
struct Writer {
    /// One entry per open link: whether its destination was safe to emit. A
    /// stack, not a flag, because links nest.
    link_stack: Vec<bool>,
    /// How many images currently have their own alt text suppressed, because
    /// the image itself was emitted.
    suppress_image_text: usize,
    /// Rendered footnote bodies, by label.
    footnotes: HashMap<String, String>,
    /// Whether a footnote body is being rendered. A definition that refers to
    /// itself would otherwise recurse until the stack ran out.
    in_footnote: bool,
    /// How many list levels deep the current block sits, which is what indents a
    /// list nested inside a list item.
    depth: usize,
    /// How many block quotes deep the current block sits, which sets how far a
    /// quote's left bar is indented.
    quote_depth: usize,
    /// The note's own folder, canonicalised, and the boundary every image path
    /// is checked against. `None` when it could not be resolved: every image is
    /// then a marker, which is the answer a platform with no filesystem — the
    /// wasm frontend — has to give as well.
    note_folder: Option<PathBuf>,
}

impl Writer {
    /// Render every block in `events`, each followed by a blank line.
    ///
    /// Written as an index walk because an unmodelled event has to be able to
    /// say "skip me" without descending into it: descending into a start whose
    /// end is never found is unbounded recursion.
    fn blocks(&mut self, events: &[Event<'_>], out: &mut String) {
        let mut index = 0;
        while index < events.len() {
            index += self.block(&events[index..], out);
        }
    }

    /// Render one block, returning how many events it used.
    ///
    /// Never returns zero: an event that starts no block this module models is
    /// consumed one at a time, so an unmodelled event cannot spin the walk.
    fn block(&mut self, events: &[Event<'_>], out: &mut String) -> usize {
        let Some(first) = events.first() else {
            return 1;
        };
        let tail = &events[1..];
        match first {
            Event::Rule => {
                out.push_str("#line(length: 100%)\n\n");
                1
            }
            Event::Start(Tag::Paragraph) => {
                let (inline, used) =
                    take_until(tail, |e| matches!(e, Event::End(TagEnd::Paragraph)));
                let mut text = String::new();
                self.inline(&inline, &mut text);
                out.push_str(&text);
                out.push_str("\n\n");
                used + 2
            }
            Event::Start(Tag::Heading { level, .. }) => {
                let (inline, used) =
                    take_until(tail, |e| matches!(e, Event::End(TagEnd::Heading(_))));
                let mut text = String::new();
                self.inline(&inline, &mut text);
                let level = (*level as usize).clamp(1, 6);
                out.push_str(&"=".repeat(level));
                out.push(' ');
                out.push_str(&text);
                out.push_str("\n\n");
                used + 2
            }
            Event::Start(Tag::CodeBlock(kind)) => {
                let (inline, used) =
                    take_until(tail, |e| matches!(e, Event::End(TagEnd::CodeBlock)));
                let mut code = String::new();
                for event in &inline {
                    if let Event::Text(text) = event {
                        code.push_str(text);
                    }
                }
                self.code_block(code_language(code_info(kind)), &code, out);
                used + 2
            }
            Event::Start(Tag::BlockQuote(_)) => {
                let (inner, used) =
                    take_until(tail, |e| matches!(e, Event::End(TagEnd::BlockQuote(_))));
                let mut body = String::new();
                self.quote_depth += 1;
                // This quote's own depth, captured before it is released: the
                // first quote is 1em in, the one inside it 2em.
                let depth = self.quote_depth;
                self.blocks(&inner, &mut body);
                self.quote_depth -= 1;
                let body = body.trim_matches('\n');
                if !body.is_empty() {
                    // A `#block` with a left stroke, not a `>` on every line:
                    // Typst 0.15 typesets a leading `>` as the *character*, so a
                    // quote written that way comes out as a paragraph full of
                    // angle brackets. Verified by rendering the page.
                    out.push_str(&format!(
                        "#block(inset: (left: {depth}em), stroke: (left: 2pt), width: 100%)[{body}]\n\n"
                    ));
                }
                used + 2
            }
            Event::Start(Tag::List(start)) => {
                let (inner, used) = take_list(tail);
                self.list(start.is_some(), &inner, out, self.depth);
                used + 2
            }
            Event::Start(Tag::Table(_)) => {
                let (inner, used) = take_until(tail, |e| matches!(e, Event::End(TagEnd::Table)));
                self.table(&inner, out);
                used + 2
            }
            // The definition site of a footnote. The body was already rendered
            // into the reference, so nothing is emitted here — but the whole
            // definition is consumed, or it would be rendered twice.
            Event::Start(Tag::FootnoteDefinition(_)) => {
                let (_, used) = take_until(tail, |e| {
                    matches!(e, Event::End(TagEnd::FootnoteDefinition))
                });
                used + 2
            }
            // Raw HTML from the document: dropped, like in the HTML renderer.
            Event::Html(_) | Event::InlineHtml(_) => 1,
            Event::Start(Tag::HtmlBlock) => 1,
            // Text that reached block level means the stream held something this
            // module does not model wrapped around it. Rendering the words is
            // better than dropping them; the enclosing walk then carries on
            // through whatever else follows.
            Event::Text(text) => {
                self.text(text, out);
                out.push_str("\n\n");
                1
            }
            // Anything else: one event, unrendered. Never zero, so the walk
            // advances.
            _ => 1,
        }
    }

    /// One fenced code block.
    fn code_block(&self, language: Option<String>, code: &str, out: &mut String) {
        // The language goes *after* the opening fence, not on its own line: that
        // is Typst's info-string position, and it is what turns on syntax
        // highlighting.
        let fence = fence_for(code);
        out.push_str(&fence);
        if let Some(language) = &language {
            out.push_str(language);
        }
        out.push('\n');
        for line in code.trim_end_matches('\n').split('\n') {
            // A blank line inside the block would end it early, so empty lines
            // are emitted with the fence's indentation.
            if line.is_empty() {
                out.push_str(&" ".repeat(fence.len()));
                out.push('\n');
            } else {
                out.push_str(line);
                out.push('\n');
            }
        }
        out.push_str(&fence);
        out.push_str("\n\n");
    }

    /// A list, rendered item by item.
    ///
    /// Each item's own blocks are rendered first and then spliced in with the
    /// marker on the first line and the continuation indented to match. Doing it
    /// this way rather than tracking an indent depth as events stream past is
    /// what makes a list nested inside a list item land at the right column.
    fn list(&mut self, ordered: bool, events: &[Event<'_>], out: &mut String, depth: usize) {
        let marker = if ordered { '+' } else { '-' };
        let indent = "  ".repeat(depth);
        let mut index = 0;
        while index < events.len() {
            if !matches!(events[index], Event::Start(Tag::Item)) {
                index += 1;
                continue;
            }
            let (inner, used) = take_item(&events[index + 1..]);
            index += used + 2;

            // A task marker belongs on the item's own line, before its text.
            //
            // Only the item's *own leading* markers are lifted out. Filtering the
            // whole item would also take the markers of any list nested inside
            // it, and the nested items would then render with no checkbox at all
            // — the same class of silent loss as a truncated item.
            let mut done = None;
            let mut seen_content = false;
            let content: Vec<Event<'_>> = inner
                .iter()
                .filter(|event| match event {
                    Event::TaskListMarker(checked) if !seen_content => {
                        done = done.or(Some(*checked));
                        false
                    }
                    _ => {
                        seen_content = true;
                        true
                    }
                })
                .cloned()
                .collect();

            // The item's own blocks are rendered one level deeper, which is what
            // puts a list nested inside this item at the next column.
            let mut body = String::new();
            self.depth = depth + 1;
            self.blocks(&content, &mut body);
            self.depth = depth;

            // Blank lines are dropped inside an item: Typst reads a blank line
            // as the end of the item, so a loose markdown list would otherwise
            // come out as several one-line lists.
            let mut lines = body.lines().filter(|line| !line.trim().is_empty());
            // The first line carries the marker, so its own indent is replaced
            // by `indent` plus the two columns the marker takes.
            out.push_str(&indent);
            out.push(marker);
            out.push(' ');
            if let Some(done) = done {
                out.push_str(checkbox(done));
                out.push(' ');
            }
            out.push_str(lines.next().unwrap_or("").trim_start());
            out.push('\n');
            // Continuation lines are emitted **verbatim**, indentation included.
            // They were rendered one level deeper, which lands them exactly two
            // columns past the marker — where Typst needs them to be — and
            // re-indenting or trimming them here would flatten the nesting.
            for line in lines {
                out.push_str(line);
                out.push('\n');
            }
        }
        out.push('\n');
    }

    /// One `#table(...)` call.
    ///
    /// `stroke` is set because a Typst table has no lines by default, and a
    /// borderless grid of numbers does not read as a table.
    fn table(&mut self, events: &[Event<'_>], out: &mut String) {
        let mut rows: Vec<Vec<String>> = Vec::new();
        let mut row: Vec<String> = Vec::new();
        // GFM always emits a head, so the first row is the header unless the
        // document had none at all.
        let mut header = false;
        let mut cell: Option<String> = None;

        for event in events {
            match event {
                // The header's cells arrive without a `TableRow` around them,
                // so the head row is pushed when the head closes rather than on
                // a row end. Without this the header row is dropped and the
                // first body row is typeset as the header.
                Event::Start(Tag::TableHead) => {
                    header = true;
                    row.clear();
                }
                Event::End(TagEnd::TableHead) => rows.push(std::mem::take(&mut row)),
                Event::Start(Tag::TableRow) => row.clear(),
                Event::End(TagEnd::TableRow) => rows.push(std::mem::take(&mut row)),
                Event::Start(Tag::TableCell) => cell = Some(String::new()),
                Event::End(TagEnd::TableCell) => {
                    if let Some(text) = cell.take() {
                        row.push(text);
                    }
                }
                other => {
                    if let Some(text) = cell.as_mut() {
                        self.inline_one(other, text);
                    }
                }
            }
        }

        let columns = rows.iter().map(Vec::len).max().unwrap_or(1).max(1);
        out.push_str("#table(\n");
        out.push_str(&format!("  columns: {columns},\n"));
        out.push_str("  stroke: 0.5pt,\n");
        for (index, cells) in rows.iter().enumerate() {
            // Cells are content blocks, so the escaped markup goes in as
            // written and a `]` in the document cannot close one.
            let list = cells
                .iter()
                .map(|cell| format!("[{}]", cell.replace('\n', " ")))
                .collect::<Vec<_>>()
                .join(", ");
            if header && index == 0 {
                out.push_str(&format!("  table.header({list}),\n"));
            } else {
                out.push_str(&format!("  {list},\n"));
            }
        }
        out.push_str(")\n\n");
    }

    /// Render the inline events of one block.
    fn inline(&mut self, events: &[Event<'_>], out: &mut String) {
        // Merged first: `pulldown-cmark` splits one paragraph into several
        // `Text` events wherever markdown syntax *might* start — a lone `_`, a
        // `[`, an escaped `\\`. A math span like `$\sum_{i=0}^{n}$` is split
        // across three of them, and split per event it is not a math span at
        // all: the opening `$` ends up in one event and the closing `$` in
        // another, so the formula is typeset as escaped prose. Adjacent text
        // events are contiguous in the source, so merging them restores the
        // span without changing what the document said.
        for event in coalesce_text(events) {
            self.inline_one(&event, out);
        }
    }

    fn inline_one(&mut self, event: &Event<'_>, out: &mut String) {
        match event {
            // A text node inside an image that was emitted: the alt text has
            // already served as that image's content, so it must not appear a
            // second time.
            Event::Text(text) if self.suppress_image_text > 0 => {}
            Event::Text(text) => self.text(text, out),
            Event::Code(code) => out.push_str(&inline_code(code)),
            Event::SoftBreak => out.push('\n'),
            Event::HardBreak => out.push_str("\\\n"),
            Event::Start(Tag::Emphasis) => out.push('_'),
            Event::End(TagEnd::Emphasis) => out.push('_'),
            Event::Start(Tag::Strong) => out.push('*'),
            Event::End(TagEnd::Strong) => out.push('*'),
            Event::Start(Tag::Strikethrough) => out.push_str("#strike["),
            Event::End(TagEnd::Strikethrough) => out.push(']'),
            Event::Start(Tag::Link { dest_url, .. }) => {
                let safe = is_safe_url(dest_url);
                if let Some(url) = safe.then(|| quote_string(dest_url.as_ref())) {
                    out.push_str(&format!("#link({url})["));
                }
                self.link_stack.push(safe);
            }
            Event::End(TagEnd::Link) => {
                // Only close a bracket we opened. A dropped wrapper keeps its
                // text and nothing else, so the `]` has to follow the decision.
                if self.link_stack.pop().unwrap_or(false) {
                    out.push(']');
                }
            }
            Event::Start(Tag::Image { dest_url, .. }) => self.image(dest_url.as_ref(), out),
            Event::End(TagEnd::Image) => {
                if self.suppress_image_text > 0 {
                    self.suppress_image_text -= 1;
                }
            }
            Event::FootnoteReference(label) => {
                // Cloned rather than borrowed: rendering the body needs
                // `&mut self`, and the `in_footnote` flag is what stops a
                // definition that refers to itself from recursing forever.
                let body = if self.in_footnote {
                    None
                } else {
                    self.footnotes.get(label.as_ref()).cloned()
                };
                match body {
                    // Typst places a footnote at the foot of the page it is
                    // referenced from, which is what `#footnote` is for.
                    Some(body) => {
                        // The body is block content, so it is rendered as blocks
                        // and then trimmed: `#footnote[…]\\n\\n` would put the
                        // closing bracket on a line of its own inside the
                        // content block, which the compiler reads as content
                        // rather than as the end of the call.
                        let mut rendered = String::new();
                        self.in_footnote = true;
                        self.blocks(&parse(&body), &mut rendered);
                        self.in_footnote = false;
                        out.push_str("#footnote[");
                        out.push_str(rendered.trim_matches('\n'));
                        out.push(']');
                    }
                    // Undefined, or a reference inside a footnote body: show the
                    // label rather than losing the marker.
                    None => out.push_str(&escape_text(&format!("[^{label}]"))),
                }
            }
            // Raw HTML from the document: dropped, like in the HTML renderer.
            Event::Html(_) | Event::InlineHtml(_) => {}
            Event::Start(Tag::HtmlBlock) | Event::End(TagEnd::HtmlBlock) => {}
            // Block-level markers can reach the inline pass from inside a footnote
            // body. Dropping them is the whole treatment: recursing into the
            // same event would never terminate.
            _ => {}
        }
    }

    /// One image reference: the `#image` call, or the marker that replaces it.
    fn image(&mut self, dest: &str, out: &mut String) {
        // A remote image cannot work: the compiler has no network and a `data:`
        // URL is not an image to it either. Nothing is emitted for it and the
        // alt text is left in place — the useful part of a picture that cannot
        // be shown.
        if !is_local_image(dest) {
            return;
        }
        match image_argument(dest, self.note_folder.as_deref()) {
            Ok(argument) => {
                out.push_str("#image(");
                out.push_str(&argument);
                out.push(')');
            }
            Err(why) => out.push_str(&missing_image(dest, why)),
        }
        // Either way the alt text has done its job: as the image's content, or
        // as something the marker already names. Printing it as well would put
        // the same information in the page twice.
        self.suppress_image_text += 1;
    }

    /// Document text, with math expanded by the shared splitter.
    ///
    /// Math goes through [`split_math`], the same detector the preview uses, so
    /// `$5 and $10` stays prose in the PDF exactly as it stays prose on screen.
    ///
    /// The TeX is then *translated* rather than passed through: Typst has no
    /// `\frac` and no `\sum`, and a single untranslated formula fails the whole
    /// compilation. See [`typst_math`] for the measured mapping.
    fn text(&mut self, text: &str, out: &mut String) {
        for piece in split_math(text) {
            match piece {
                MathPiece::Text(t) => out.push_str(&escape_text(&t)),
                MathPiece::Inline(tex) => {
                    out.push('$');
                    out.push_str(tex_to_typst(&tex).trim());
                    out.push('$');
                }
                MathPiece::Display(tex) => {
                    // A display formula gets a paragraph of its own, which is how
                    // Typst lays it out centred — and an `align`, which KaTeX
                    // spans over several rows, becomes several paragraphs.
                    for block in tex_to_typst_blocks(&tex) {
                        out.push_str("\n\n$ ");
                        out.push_str(block.trim());
                        out.push_str(" $\n\n");
                    }
                }
            }
        }
    }
}

/// The info string of a fenced code block, if it has one.
fn code_info<'a>(kind: &'a pulldown_cmark::CodeBlockKind<'a>) -> Option<&'a str> {
    match kind {
        pulldown_cmark::CodeBlockKind::Fenced(info) => Some(info.as_ref()),
        pulldown_cmark::CodeBlockKind::Indented => None,
    }
}

/// Merge runs of adjacent `Text` events.
///
/// The markdown parser emits one `Text` event per stretch it did not have to
/// break for syntax: `$\sum_{i=0}^{n}$` arrives as `$\sum`, `_`,
/// `{i=0}^{n}$`. Merging is safe because two adjacent text events are adjacent
/// in the source, and it is what lets a math span straddling one of those breaks
/// be recognised as a span.
fn coalesce_text<'a>(events: &'a [Event<'a>]) -> Vec<Event<'a>> {
    let mut out: Vec<Event<'a>> = Vec::with_capacity(events.len());
    for event in events {
        match (out.last_mut(), event) {
            (Some(Event::Text(previous)), Event::Text(current)) => {
                // `CowStr` has no `to_mut`, and an owned `String` is the only
                // shape that can grow, so the merged pair becomes one.
                let mut merged = String::new();
                merged.push_str(previous);
                merged.push_str(current);
                *previous = CowStr::from(merged);
            }
            _ => out.push(event.clone()),
        }
    }
    out
}

/// Collect the events up to, but not including, the first one matching `stop`.
fn take_until<'a>(
    events: &'a [Event<'a>],
    stop: impl Fn(&Event<'a>) -> bool,
) -> (Vec<Event<'a>>, usize) {
    let mut out = Vec::new();
    for (index, event) in events.iter().enumerate() {
        if stop(event) {
            return (out, index);
        }
        out.push(event.clone());
    }
    (out, events.len())
}

/// Collect the events of a list or a list item, stopping at its *matching* end.
///
/// A plain [`take_until`] is wrong for both, and wrong silently: a nested list
/// carries its own `End(List)` and `End(Item)`, so the outer one would be cut
/// short at the inner one. For a list that leaves the outer items to be picked
/// up by the enclosing walk at the wrong indent; for an item it swallows the
/// nested list whole and takes the nested item's `TaskListMarker` for its own.
///
/// So the depth of open lists is tracked, and only a terminator at depth zero
/// ends the construct.
fn take_nesting<'a>(
    events: &'a [Event<'a>],
    start: impl Fn(&Event<'a>) -> bool,
    end: impl Fn(&Event<'a>) -> bool,
) -> (Vec<Event<'a>>, usize) {
    let mut out = Vec::new();
    let mut depth = 0usize;
    for (index, event) in events.iter().enumerate() {
        if depth == 0 && end(event) {
            return (out, index);
        }
        if start(event) {
            depth += 1;
        } else if end(event) {
            depth = depth.saturating_sub(1);
        }
        out.push(event.clone());
    }
    (out, events.len())
}

/// One list's events, stopping at its matching `End(List)`.
fn take_list<'a>(events: &'a [Event<'a>]) -> (Vec<Event<'a>>, usize) {
    take_nesting(
        events,
        |e| matches!(e, Event::Start(Tag::List(_))),
        |e| matches!(e, Event::End(TagEnd::List(_))),
    )
}

/// One list item's events, stopping at its matching `End(Item)`.
fn take_item<'a>(events: &'a [Event<'a>]) -> (Vec<Event<'a>>, usize) {
    take_nesting(
        events,
        |e| matches!(e, Event::Start(Tag::Item)),
        |e| matches!(e, Event::End(TagEnd::Item)),
    )
}

/// Render the footnote definitions, keyed by label.
///
/// Separated from the main pass because a reference precedes its definition in
/// ordinary markdown, and the reference is where `#footnote` has to be emitted.
fn collect_footnotes(events: &[Event<'_>], note_folder: &Path) -> HashMap<String, String> {
    let mut out = HashMap::new();
    let mut index = 0;
    while index < events.len() {
        let Event::Start(Tag::FootnoteDefinition(label)) = &events[index] else {
            index += 1;
            continue;
        };
        let (inner, used) = take_until(&events[index + 1..], |e| {
            matches!(e, Event::End(TagEnd::FootnoteDefinition))
        });
        let mut writer = Writer {
            link_stack: Vec::new(),
            suppress_image_text: 0,
            footnotes: HashMap::new(),
            in_footnote: false,
            depth: 0,
            quote_depth: 0,
            // The same folder as the body, so an image inside a footnote is
            // checked exactly like one outside it.
            note_folder: note_folder.canonicalize().ok(),
        };
        let mut body = String::new();
        writer.blocks(&inner, &mut body);
        out.insert(label.to_string(), body.trim_matches('\n').to_string());
        index += used + 2;
    }
    out
}

/// Parse `text` with the same options the rest of the app uses.
fn parse(text: &str) -> Vec<Event<'_>> {
    Parser::new_ext(text, parser_options()).collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A note folder on disk, deleted when the test ends.
    ///
    /// Real directories, never a mock: what is being decided is a question about
    /// the filesystem — whether a path resolves, and *where* it lands — and a
    /// mock of `exists` cannot answer the second one.
    ///
    /// The note lives in a `notas` subfolder of the scratch directory, so a test
    /// can plant something a `..` actually reaches.
    struct Note {
        root: PathBuf,
        folder: PathBuf,
    }

    impl Note {
        fn new(tag: &str) -> Self {
            let root = std::env::temp_dir().join(format!(
                "codedocs-typst-{tag}-{}-{:?}",
                std::process::id(),
                std::thread::current().id()
            ));
            let _ = std::fs::remove_dir_all(&root);
            let folder = root.join("notas");
            std::fs::create_dir_all(&folder).expect("create the note's folder");
            // Canonicalised: the containment check compares canonical paths, and
            // a scratch folder behind a symlink (`/tmp` on macOS) would
            // otherwise never compare equal to itself.
            Note {
                root: root.canonicalize().expect("canonicalize the scratch dir"),
                folder: folder
                    .canonicalize()
                    .expect("canonicalize the note's folder"),
            }
        }

        fn folder(&self) -> &Path {
            &self.folder
        }

        /// Write a file inside the note's folder, folders included.
        fn write(&self, relative: &str, body: &str) -> &Self {
            let path = self.folder.join(relative);
            std::fs::create_dir_all(path.parent().unwrap()).expect("create the parent");
            std::fs::write(&path, body).expect("write the fixture");
            self
        }

        /// Write a file *outside* the note's folder, and return its path.
        fn plant(&self, relative: &str, body: &str) -> PathBuf {
            let path = self.root.join(relative);
            std::fs::write(&path, body).expect("plant the file");
            path
        }
    }

    impl Drop for Note {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.root);
        }
    }

    /// The body without the preamble, so the assertions read as assertions
    /// about the document rather than about the page setup.
    ///
    /// The note's folder is a real, empty one: image paths are resolved against
    /// it, so a path with nothing behind it resolves to nothing. That is the
    /// right folder for a markdown with no images, and the tests that do have
    /// one go through [`body_in`] with the file actually there.
    fn body(markdown: &str) -> String {
        let note = Note::new("body");
        body_in(markdown, note.folder())
    }

    /// The body, for a note that lives in `folder`.
    fn body_in(markdown: &str, folder: &Path) -> String {
        let typst = markdown_to_typst(markdown, folder);
        let start = typst
            .find("\n\n")
            .expect("the preamble ends with a blank line")
            + 2;
        typst[start..].trim().to_string()
    }

    fn full(markdown: &str) -> String {
        let note = Note::new("full");
        markdown_to_typst(markdown, note.folder())
    }

    #[test]
    fn preamble_sets_the_page_up() {
        let note = Note::new("preamble");
        let typst = markdown_to_typst("# hola\n", note.folder());
        assert!(
            typst.contains(r#"#set page(paper: "a4", margin: 2.5cm)"#),
            "{typst}"
        );
        assert!(typst.contains("#set text(size: 11pt)"), "{typst}");
        assert!(typst.contains("#set par(justify: true)"), "{typst}");
        // No `font:`: a font name the compiler does not have fails the build.
        assert!(!typst.contains("font:"), "{typst}");
    }

    #[test]
    fn headings_use_the_typst_marker_per_level() {
        assert_eq!(body("# Uno\n"), "= Uno");
        assert_eq!(body("### Tres\n"), "=== Tres");
        assert_eq!(body("###### Seis\n"), "====== Seis");
    }

    #[test]
    fn setext_headings_become_typst_headings() {
        assert_eq!(body("Titulo\n======\n"), "= Titulo");
    }

    #[test]
    fn emphasis_and_strong_use_the_typst_markers() {
        assert_eq!(body("*suave* y **fuerte**\n"), "_suave_ y *fuerte*");
    }

    #[test]
    fn strikethrough_is_a_strike_element() {
        assert_eq!(body("~~gone~~\n"), "#strike[gone]");
    }

    #[test]
    fn paragraphs_are_separated_by_a_blank_line() {
        assert_eq!(body("uno\n\ndos\n"), "uno\n\ndos");
    }

    #[test]
    fn nested_lists_indent_by_two_spaces() {
        assert_eq!(
            body("- uno\n  - dos\n    - tres\n"),
            "- uno\n  - dos\n    - tres"
        );
    }

    #[test]
    fn ordered_lists_use_the_plus_marker() {
        assert_eq!(body("1. uno\n2. dos\n"), "+ uno\n+ dos");
    }

    // ---- Task lists ----

    #[test]
    fn task_lists_are_drawn_not_passed_through() {
        let typst = body("- [ ] pendiente\n- [x] hecha\n");
        // The markdown spelling must not survive as literal text.
        assert!(!typst.contains("[ ]"), "{typst}");
        assert!(!typst.contains("[x]"), "{typst}");
        // One marker per item, and the checked one is drawn differently.
        assert_eq!(typst.matches("#box(stroke:").count(), 2, "{typst}");
        assert_eq!(typst.matches("#curve(").count(), 1, "{typst}");
    }

    #[test]
    fn a_task_inside_a_nested_list_keeps_its_marker() {
        let typst = body("- [x] hecha\n  - [ ] pendiente\n");
        // One marker per item, and only the checked one is drawn differently.
        assert_eq!(typst.matches("#box(stroke:").count(), 2, "{typst}");
        assert_eq!(typst.matches("#curve(").count(), 1, "{typst}");
        // The nested marker sits on the *nested* item's line, indented with it.
        // Lifting every marker out of the outer item's events — or cutting the
        // outer item short at the nested list's own `End(Item)` — leaves the
        // nested item with no checkbox at all, silently.
        assert!(
            typst.contains("\n  - #box(stroke: 0.5pt, width: 0.75em"),
            "the nested checkbox is missing or misplaced: {typst}"
        );
    }

    // ---- Quote ----

    #[test]
    fn a_quote_is_a_block_with_a_left_bar() {
        // Not a `>` on every line: Typst 0.15 typesets a leading `>` as the
        // character, so that spelling is a paragraph of angle brackets.
        assert_eq!(
            body("> uno\n>\n> dos\n"),
            "#block(inset: (left: 1em), stroke: (left: 2pt), width: 100%)[uno\n\ndos]"
        );
    }

    #[test]
    fn a_nested_quote_is_indented_further() {
        assert_eq!(
            body("> uno\n>\n> > dos\n"),
            "#block(inset: (left: 1em), stroke: (left: 2pt), width: 100%)[uno\n\n\
             #block(inset: (left: 2em), stroke: (left: 2pt), width: 100%)[dos]]"
        );
    }

    #[test]
    fn an_empty_quote_emits_no_block() {
        assert_eq!(body("> \n"), "");
    }

    #[test]
    fn a_quote_can_hold_a_list() {
        // The body is rendered as blocks and then wrapped, so a quote with a
        // list in it keeps the list.
        let typst = body("> - uno\n> - dos\n");
        assert!(typst.starts_with("#block(inset: (left: 1em)"), "{typst}");
        assert!(typst.contains("- uno"), "{typst}");
    }

    // ---- Table ----

    #[test]
    fn a_table_becomes_one_table_call_with_lines() {
        assert_eq!(
            body("| a | b |\n|---|---|\n| 1 | 2 |\n"),
            "#table(\n  columns: 2,\n  stroke: 0.5pt,\n  table.header([a], [b]),\n  [1], [2],\n)"
        );
    }

    #[test]
    fn the_first_row_is_the_header_not_a_body_row() {
        // The header's cells arrive without a `TableRow` around them, so the row
        // is only pushed when the head closes. Missing that put the first *body*
        // row in `table.header` and dropped the header entirely.
        let typst = body("| a | b |\n|---|---|\n| 1 | 2 |\n");
        assert!(typst.contains("table.header([a], [b]),"), "{typst}");
        assert!(!typst.contains("table.header([1]"), "{typst}");
    }

    #[test]
    fn a_table_with_several_body_rows() {
        let typst = body("| a | b |\n|---|---|\n| 1 | 2 |\n| 3 | 4 |\n");
        assert!(typst.contains("table.header([a], [b]),"), "{typst}");
        assert!(typst.contains("  [3], [4],"), "{typst}");
    }

    #[test]
    fn a_ragged_table_pads_to_its_widest_row() {
        let typst = body("| a | b |\n|---|---|\n| 1 |\n");
        assert!(typst.contains("columns: 2"), "{typst}");
    }

    #[test]
    fn table_cells_keep_their_inline_markup() {
        // Cells are content blocks, so inline markup works inside them — which
        // is the point of routing cells through the inline writer instead of
        // escaping everything.
        let typst = body("| a | b |\n|---|---|\n| *x* | `y` |\n");
        assert!(typst.contains("[_x_]"), "{typst}");
        assert!(typst.contains("[``` y```]"), "{typst}");
    }

    // ---- Code ----

    #[test]
    fn a_fenced_block_carries_its_language() {
        assert_eq!(
            body("```rust\nfn main() {}\n```\n"),
            "```rust\nfn main() {}\n```"
        );
    }

    #[test]
    fn a_block_without_a_language_has_no_tag() {
        assert_eq!(body("```\ncode\n```\n"), "```\ncode\n```");
    }

    #[test]
    fn an_indented_block_is_a_plain_fence() {
        assert_eq!(body("para\n\n    code\n"), "para\n\n```\ncode\n```");
    }

    #[test]
    fn a_block_containing_backticks_gets_a_longer_fence() {
        // The inner run of three must not close the block early: the fence is
        // two backticks longer, which is the rule measured against the
        // compiler. A fence of exactly three here compiles *successfully* and
        // prints `dentro` without its backticks, so this asserts the exact
        // output rather than "a fence exists".
        assert_eq!(
            body("````text\n```dentro\n```\n````\n"),
            "`````text\n```dentro\n```\n`````"
        );
    }

    #[test]
    fn fence_length_grows_with_the_content() {
        // The rule itself, so a change to it is deliberate. `+2` and a floor of
        // 3; see `fence_for`.
        assert_eq!(fence_len("code"), 3);
        assert_eq!(fence_len("a`b"), 3);
        assert_eq!(fence_len("a``b"), 4);
        assert_eq!(fence_len("a```b"), 5);
    }

    #[test]
    fn a_blank_line_inside_a_block_keeps_the_fence_open() {
        let typst = body("```py\nuno\n\ndos\n```\n");
        assert!(typst.contains("uno\n   \ndos"), "{typst}");
    }

    #[test]
    fn a_hostile_fence_label_cannot_become_anything_else() {
        let typst = body("```{#x\" onload=\"alert(1)}\ncode\n```\n");
        assert!(!typst.contains("onload=\"alert"), "{typst}");
        assert!(typst.contains("code"), "{typst}");
    }

    #[test]
    fn inline_code_is_a_padded_fence() {
        // The padding is what stops Typst reading the first word as a language
        // tag: `` ```x``` `` typesets `x` as the tag and drops the content.
        assert_eq!(body("usa `code` aqui\n"), "usa ``` code``` aqui");
    }

    #[test]
    fn inline_code_with_backticks_gets_a_longer_fence() {
        assert_eq!(body("usa ``a`b`` aqui\n"), "usa ``` a`b``` aqui");
    }

    #[test]
    fn inline_code_keeps_a_backtick_run_intact() {
        // The inner run is never closed early: one backtick of content in a
        // three-backtick fence prints as `a`b`, where a two-backtick fence would
        // compile cleanly and silently print `ab`.
        assert_eq!(body("x ``a`b`` y\n"), "x ``` a`b``` y");
    }

    // ---- Math ----

    #[test]
    fn inline_math_is_passed_to_typst_verbatim() {
        assert_eq!(body("valor $x^2$ aqui\n"), "valor $x^2$ aqui");
    }

    #[test]
    fn an_exponent_with_braces_reaches_the_math_whole() {
        // The trap this test exists for: `e^{i\pi}` has to arrive as one math
        // span. `pulldown-cmark` emits the whole run as a single `Text` event —
        // it is *not* an inline code block, which is what would have eaten the
        // braces — so `split_math` sees one clean candidate.
        //
        // The braces become parentheses because Typst needs them there, and
        // `\pi` becomes `pi`: the TeX is translated, not passed through,
        // because Typst has no `\pi`. What must survive is the *shape* — one
        // math span holding both `i` and `pi`, with nothing dropped between
        // them.
        assert_eq!(body("$e^{i\\pi}$\n"), "$e^(i pi)$");
    }

    #[test]
    fn display_math_gets_its_own_paragraph() {
        assert_eq!(body("$$\\frac{a}{b}$$\n"), "$ frac(a, b) $");
    }

    #[test]
    fn currency_is_escaped_rather_than_opening_math() {
        // Unescaped, this is an unclosed math delimiter and the *whole*
        // compilation fails with "unclosed delimiter".
        assert_eq!(body("cuesta $5 y $10\n"), "cuesta \\$5 y \\$10");
    }

    #[test]
    fn a_dollar_inside_inline_code_is_not_math() {
        // Raw content is literal, so the `$` needs no escape here — and must not
        // get one, which would print a backslash in the PDF.
        assert_eq!(body("corre `echo $HOME`\n"), "corre ``` echo $HOME```");
    }

    #[test]
    fn math_inside_a_fenced_block_is_left_alone() {
        assert_eq!(body("```sh\necho $HOME\n```\n"), "```sh\necho $HOME\n```");
    }

    // ---- Links and images ----

    #[test]
    fn a_safe_link_becomes_a_link_element() {
        assert_eq!(
            body("ver [docs](https://example.test/a)\n"),
            r#"ver #link("https://example.test/a")[docs]"#
        );
    }

    #[test]
    fn a_relative_link_survives() {
        assert_eq!(
            body("ver [otra](./notas/otra.md)\n"),
            r#"ver #link("./notas/otra.md")[otra]"#
        );
    }

    #[test]
    fn an_unsafe_link_keeps_its_text_and_drops_the_destination() {
        let typst = body("[click](javascript:alert(1))\n");
        assert!(!typst.contains("javascript:"), "{typst}");
        assert!(typst.contains("click"), "{typst}");
        assert!(!typst.contains("#link"), "{typst}");
    }

    #[test]
    fn a_link_around_an_image_closes_its_own_bracket() {
        let note = Note::new("link-image");
        note.write("a.png", "x");
        let typst = body_in("[![alt](./a.png)](https://ok.test)\n", note.folder());
        assert_eq!(typst, r##"#link("https://ok.test")[#image("./a.png")]"##);
    }

    #[test]
    fn a_url_cannot_close_its_own_string_literal() {
        // The one place a string literal is used, so the one place a stray quote
        // or backslash would turn into code. `#read` can read files, which is
        // what makes a breakout here a sandbox escape and not a typo.
        //
        // The destination comes from the *document*, so the payload is the
        // classic one: close the literal, then call something.
        let typst = body("[x](https://ok.test/a%22+code+%22)\n");
        assert_eq!(typst, r####"#link("https://ok.test/a%22+code+%22")[x]"####);

        // Now the same thing with a real quote in the destination, which is the
        // character that can actually close a Typst literal. Without escaping it
        // the literal would end mid-URL and the rest would be compiled as code.
        let note = Note::new("url-quote");
        let quoted = markdown_to_typst("[x](<https://ok.test/\"+code+\">)\n", note.folder());
        let expected = "#link(\"https://ok.test/\\\"+code+\\\"\")[x]";
        assert!(
            quoted.contains(expected),
            "a quote in the URL was not escaped: {quoted}"
        );
        // And the payload is still inside: the literal's closing quote is
        // followed by the link's own `)`, with nothing the compiler would run.
        let literal_end = quoted.find(expected).expect("checked above") + expected.len();
        assert_eq!(&quoted[literal_end..], "", "{quoted}");
    }

    #[test]
    fn a_url_with_a_backslash_stays_inside_the_literal() {
        let typst = body("[x](<https://ok.test/a\\b.png>)\n");
        assert_eq!(typst, r####"#link("https://ok.test/a\\b.png")[x]"####);
    }

    #[test]
    fn a_relative_image_becomes_an_image_element() {
        let note = Note::new("relative");
        note.write("img.png", "x");
        assert_eq!(
            body_in("![pie](./img.png)\n", note.folder()),
            r#"#image("./img.png")"#
        );
    }

    #[test]
    fn a_windows_image_path_is_normalised() {
        let note = Note::new("windows");
        note.write("img/carpeta/foto.png", "x");
        assert_eq!(
            body_in("![pie](img\\carpeta\\foto.png)\n", note.folder()),
            r#"#image("img/carpeta/foto.png")"#
        );
    }

    // ---- Images: the path is resolved and checked before it reaches Typst ----
    //
    // Two questions, both about the filesystem, both answered where the `.typ`
    // is generated: does the file exist, and does it land inside the note's own
    // folder. Typst has no try/catch, so a reference it cannot resolve is not a
    // missing picture — it is the whole document failing to compile.
    //
    // Every test here builds real files in a real folder. What is under test is
    // a decision made about the filesystem, so a mock would be testing the mock.

    #[test]
    fn an_image_inside_the_note_folder_is_emitted() {
        let note = Note::new("exists");
        note.write("foto.png", "lo que tenga adentro da igual");
        assert_eq!(
            body_in("![pie](foto.png)\n", note.folder()),
            r#"#image("foto.png")"#
        );
    }

    #[test]
    fn an_image_in_a_subfolder_of_the_note_folder_is_emitted() {
        // A subfolder is *inside* the note's folder. This is the shape nearly
        // every real notes tree uses — `img/diagrams/flujo.png` next to the
        // note — and a check that rejected it would reject the feature.
        let note = Note::new("subfolder");
        note.write("img/diagrams/flujo.png", "x");
        assert_eq!(
            body_in("![pie](img/diagrams/flujo.png)\n", note.folder()),
            r#"#image("img/diagrams/flujo.png")"#
        );
    }

    #[test]
    fn a_missing_image_becomes_a_marker_and_not_a_reference() {
        // The failure being fixed. Emitting `#image("rota.png")` is a Typst
        // error, and Typst has no way to catch one, so the export produced *no
        // PDF at all* and the user was told exporting did not work.
        let note = Note::new("missing");
        let typst = body_in("![pie de foto](rota.png)\n", note.folder());
        assert!(!typst.contains("#image"), "{typst}");
        // The marker names the image and says why it is not there, so the reader
        // knows something was in this spot.
        assert!(typst.contains("rota.png"), "{typst}");
        assert!(typst.contains("no existe"), "{typst}");
        // And the alt text does not come out a second time beside it.
        assert!(!typst.contains("pie de foto"), "{typst}");
    }

    #[test]
    fn a_dotdot_that_leaves_the_note_folder_becomes_a_marker() {
        let note = Note::new("dotdot");
        let planted = note.plant("secreto.png", "clave: hunter2");
        assert!(planted.exists(), "the fixture must be a real file");
        let typst = body_in("![x](../secreto.png)\n", note.folder());
        assert!(!typst.contains("#image"), "{typst}");
        assert!(typst.contains("fuera de la carpeta"), "{typst}");
    }

    #[test]
    fn an_absolute_path_outside_the_note_folder_becomes_a_marker() {
        // The direction that is not optional: with the check off, a note could
        // name any file on the disk and have it read into a PDF the user then
        // shares. CodeDocs opens folders the user did not write, so a note is
        // not to be trusted to name its own images.
        let note = Note::new("absolute");
        let secret = note.plant("secreto.png", "clave: hunter2");
        let markdown = format!("![x]({})\n", secret.display());
        let typst = body_in(&markdown, note.folder());
        assert!(!typst.contains("#image"), "{typst}");
        assert!(typst.contains("fuera de la carpeta"), "{typst}");
    }

    #[cfg(unix)]
    #[test]
    fn a_symlink_in_the_note_pointing_outside_becomes_a_marker() {
        // The one case the compiler does *not* catch for us, measured against
        // the real 0.15.1 CLI: `typst compile --root .` refuses a `..` that
        // escapes the root and refuses an absolute path, but it *follows* a
        // symlink that sits inside it. `ln -s /etc/passwd nota/atajo` plus
        // `![x](atajo)` is a real read, and this check is what closes it.
        let note = Note::new("symlink");
        let secret = note.plant("secreto.png", "clave: hunter2");
        std::os::unix::fs::symlink(&secret, note.folder().join("atajo.png")).unwrap();
        let typst = body_in("![x](atajo.png)\n", note.folder());
        assert!(!typst.contains("#image"), "{typst}");
        assert!(typst.contains("fuera de la carpeta"), "{typst}");
    }

    #[test]
    fn a_dotdot_that_lands_back_inside_the_note_folder_is_emitted() {
        // Judged by where it lands, not by having a `..` in it. Rejecting the
        // spelling instead of the resolved path would lose a legitimate image
        // for no gain — the path it reaches is inside the folder.
        let note = Note::new("midpath");
        note.write("img/foto.png", "x");
        assert_eq!(
            body_in("![x](img/../img/foto.png)\n", note.folder()),
            r#"#image("img/../img/foto.png")"#
        );
    }

    #[test]
    fn a_path_that_is_a_directory_becomes_a_marker() {
        // A directory resolves and is inside the folder, and `#image` on it is
        // still a compile error — the same "no PDF at all" as a missing file.
        let note = Note::new("directory");
        note.write("carpeta/dentro.txt", "x");
        let typst = body_in("![x](carpeta)\n", note.folder());
        assert!(!typst.contains("#image"), "{typst}");
        assert!(typst.contains("no es un archivo"), "{typst}");
    }

    #[test]
    fn a_note_folder_that_does_not_exist_leaves_every_image_a_marker() {
        // Fail closed. With no folder there is nothing to check a path against,
        // so nothing is emitted — and it is the same thing the wasm build does,
        // where there is no filesystem to ask.
        let missing = std::env::temp_dir().join("codedocs-typst-carpeta-que-no-existe");
        let typst = body_in("![x](foto.png)\n", &missing);
        assert!(!typst.contains("#image"), "{typst}");
        assert!(typst.contains("foto.png"), "{typst}");
    }

    #[test]
    fn a_marker_cannot_be_escaped_from_the_path_it_names() {
        // The marker is the one new place document text lands inside a Typst
        // content block, so the property the whole module rests on applies to
        // it too: a `]` in the path must not end the block, and a `#` must not
        // open a code expression — which in Typst can read a file.
        let note = Note::new("marker-escape");
        let typst = body_in("![x](<a]b#read(\"/etc/passwd\").png>)\n", note.folder());
        assert!(typst.contains("\\]"), "{typst}");
        assert!(typst.contains("\\#"), "{typst}");
        // Exactly one `#` that is not escaped: the one in the `#emph` we wrote.
        // Any other would be an expression the document opened, and `#read` can
        // read a file.
        let unescaped = |needle: char| {
            typst
                .char_indices()
                .filter(|(at, c)| *c == needle && !typst[..*at].ends_with('\\'))
                .count()
        };
        assert_eq!(unescaped('#'), 1, "{typst}");
        // And exactly one bracket that actually closes a block: the marker's own.
        // The path's `]` is escaped, so it cannot end the block early and leave
        // the rest of the path as markup outside it.
        assert_eq!(unescaped(']'), 1, "{typst}");
    }

    #[test]
    fn a_remote_image_falls_back_to_its_text() {
        // The compiler has no network, so an `http` image would only fail the
        // compilation. The alt text is the useful part.
        let typst = body("![pie](https://example.test/a.png)\n");
        assert!(!typst.contains("#image"), "{typst}");
        assert!(typst.contains("pie"), "{typst}");
    }

    #[test]
    fn an_image_does_not_repeat_its_alt_text() {
        let note = Note::new("alt");
        note.write("a.png", "x");
        let typst = body_in("![pie](./a.png)\n", note.folder());
        assert_eq!(typst.matches("pie").count(), 0, "{typst}");
    }

    // ---- Footnotes ----

    #[test]
    fn a_footnote_reference_carries_its_body() {
        let typst = body("texto[^1]\n\n[^1]: la nota\n");
        // The body goes where the reference is, which is what `#footnote` needs.
        assert!(typst.contains("#footnote[la nota]"), "{typst}");
        assert_eq!(typst.matches("#footnote").count(), 1, "{typst}");
    }

    #[test]
    fn an_undefined_footnote_reference_shows_its_label() {
        // `^` carries no meaning in Typst markup, so only the brackets are
        // escaped — and they have to be, or the label would open a content
        // block.
        assert_eq!(body("texto[^nada]\n"), "texto\\[^nada\\]");
    }

    // ---- Other blocks ----

    #[test]
    fn a_horizontal_rule_is_a_line() {
        assert_eq!(body("a\n\n---\n\nb\n"), "a\n\n#line(length: 100%)\n\nb");
    }

    #[test]
    fn a_hard_break_is_a_backslash_and_a_newline() {
        assert_eq!(body("uno  \ndos\n"), "uno\\\ndos");
    }

    #[test]
    fn raw_html_from_the_document_never_reaches_the_output() {
        for md in [
            "<script>alert(1)</script>\n",
            "<img src=x onerror=alert(1)>\n",
            "<div onclick=\"steal()\">hi</div>\n",
        ] {
            let typst = body(md);
            assert!(!typst.contains("<img"), "{md:?} -> {typst}");
            assert!(!typst.contains("onerror"), "{md:?} -> {typst}");
            assert!(!typst.contains("onclick"), "{md:?} -> {typst}");
            assert!(!typst.contains("alert"), "{md:?} -> {typst}");
        }
    }

    // ---- Escaping: the property the whole module rests on ----

    #[test]
    fn every_special_character_survives_escaped() {
        // Straight quotes are covered by the second assertion: the markdown
        // parser's smart punctuation rewrites them to `‘`/`’` before this module
        // ever sees them, so a document can only deliver curly ones.
        for (raw, expected) in [
            ("a\\b", "a\\\\b"),
            ("a`b", "a\\`b"),
            ("a*b", "a\\*b"),
            ("a_b", "a\\_b"),
            ("a$b", "a\\$b"),
            ("a#b", "a\\#b"),
            ("a@b", "a\\@b"),
            ("a<b", "a\\<b"),
            ("a>b", "a\\>b"),
            ("a[b", "a\\[b"),
            ("a]b", "a\\]b"),
            ("a~b", "a\\~b"),
            ("a-b", "a\\-b"),
            ("a+b", "a\\+b"),
            ("a=b", "a\\=b"),
            ("a/b", "a\\/b"),
            ("a'b", "a\\'b"),
            ("a\"b", "a\\\"b"),
            ("a{b", "a\\{b"),
            ("a}b", "a\\}b"),
        ] {
            assert_eq!(escape_text(raw), expected, "for {raw:?}");
        }
        // And the whole run at once, through a document. No angle bracket here:
        // `<i>` is raw HTML to `pulldown-cmark` and is dropped long before this
        // module sees it, so a document cannot deliver one; `escape_text` is
        // asserted on them directly in the loop above.
        assert_eq!(
            body("a\\b`c*d_e$f#g@h j[k]l~m-n+o=p/q{t}u\n"),
            "a\\\\b\\`c\\*d\\_e\\$f\\#g\\@h j\\[k\\]l\\~m\\-n\\+o\\=p\\/q\\{t\\}u"
        );
    }

    #[test]
    fn document_text_cannot_open_a_code_expression() {
        let typst = body("#read('/etc/passwd')\n");
        // A bare `#` would be a code expression, and `#read` really does read
        // files. Escaped, it is a character.
        assert!(typst.starts_with("\\#read("), "{typst}");
        // The escaped `#` is the only one in the output, so nothing in the
        // document opened an expression.
        assert_eq!(typst.matches('#').count(), 1, "{typst}");
    }

    #[test]
    fn a_paragraph_starting_with_a_marker_character_is_not_a_list() {
        assert_eq!(body("= algo\n"), "\\= algo");
        assert_eq!(body("/ algo\n"), "\\/ algo");
    }

    #[test]
    fn a_table_cell_cannot_close_its_own_content_block() {
        let typst = body("| a | b |\n|---|---|\n| x | y ] #read('/etc/passwd') |\n");
        // The `]` is escaped, so the cell content cannot end the block the cell
        // itself lives in — which is what would let the rest of the row become
        // arguments to the `#table` call.
        assert!(typst.contains("y \\] \\#read("), "{typst}");
        // The document's `#` is escaped, so the cell holds text: there is no
        // bare `#read` anywhere, only the escaped one.
        assert!(
            !typst.contains("#read") || typst.contains("\\#read"),
            "{typst}"
        );
        assert_eq!(
            typst.matches("#read").count(),
            typst.matches("\\#read").count(),
            "an unescaped `#read` reached the output: {typst}"
        );
    }

    #[test]
    fn an_empty_document_still_compiles() {
        let typst = full("");
        assert!(typst.contains("#set page("), "{typst}");
    }

    #[test]
    fn no_document_text_lands_inside_a_string_literal() {
        // The property that keeps a Typst breakout from being a file read. The
        // only strings in the output are a link's scheme-checked URL and an
        // image's path — and a path only reaches a string once it has resolved
        // to a file inside the note's own folder. A payload in prose or in code
        // must stay markup.
        for md in [
            "```\n#read(\"/etc/passwd\")\n```\n",
            "`code #read(\"/etc/passwd\")`\n",
            "texto $#read(\"/etc/passwd\")$\n",
            "- [ ] #read(\"/etc/passwd\")\n",
            "| a |\n|---|\n| #read(\"/etc/passwd\") |\n",
        ] {
            let typst = full(md);
            for (position, _) in typst.match_indices("/etc/passwd") {
                // Walk back to the quote that would have to open a string. A
                // `#link("` we emitted always sits on its own, with no line
                // break between the quote and this text.
                let head = &typst[..position];
                let quote = head.rfind('"').unwrap_or(0);
                let opening = head[..quote].rfind('"').unwrap_or(0);
                assert!(
                    opening == 0 || head[..opening].contains('\n'),
                    "document text inside a string literal for {md:?}:\n{typst}"
                );
            }
        }
    }
}
